language: ruby
rvm:
  - 2.0.0
script:
  - bundle install
  - bundle exec rake
env:
  global:
    - BARKDOG_TEST_API_KEY=31aef8b41be3ad6070ea1013b90fc9e8
    - BARKDOG_TEST_APP_KEY=d31f2d115e8a70f5647bf691081a292cd631c3be
